
PUBLIC FUNCTION mbox_ok(qt STRING, msg STRING) RETURNS ()
  MENU qt ATTRIBUTE (STYLE="dialog",COMMENT=msg)
    COMMAND "OK"
      EXIT MENU
  END MENU
END FUNCTION

PUBLIC FUNCTION mbox_yn(qt STRING, msg STRING) RETURNS BOOLEAN
  DEFINE r BOOLEAN
  MENU qt ATTRIBUTE (STYLE="dialog",COMMENT=msg)
    COMMAND "Yes"
      LET r = TRUE
      EXIT MENU
    COMMAND "No"
      LET r = FALSE
      EXIT MENU
  END MENU
  RETURN r
END FUNCTION
